[MTDSA-11772] - dependency upgrades
hmrc/mtd-identifier-lookup pull request #48
Opened 2022-05-06 11:04 UTC by DreamcastKnight

2022-05-09 10:15 UTC, BetaDraconis requested changes
sbt-plugin -> 2.8.15
simple-reactive-mongo -> hmrc-mongo

2022-05-09 10:15 UTC, BetaDraconis commented on project/AppDependencies.scala
>      "uk.gov.hmrc"                  %% "simple-reactivemongo"      % "8.0.0-play-28",
Can you please migrate this to hmrc-mongo https://github.com/hmrc/hmrc-mongo/blob/main/MIGRATION.md

2022-05-16 09:19 UTC, james-work-account requested changes

2022-05-16 09:19 UTC, james-work-account commented on project/AppDependencies.scala
> +    "uk.gov.hmrc.mongo" %% "hmrc-mongo-test-play-28" % "0.63.0"
Move to the test dependencies

2022-05-16 09:25 UTC, DreamcastKnight commented on project/AppDependencies.scala
> +    "uk.gov.hmrc.mongo" %% "hmrc-mongo-test-play-28" % "0.63.0"
where is that, sorry?

2022-05-16 10:00 UTC, merged